# Generated by Django 5.0 on 2023-12-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Project title')),
                ('description', models.TextField(verbose_name='Project description')),
                ('image', models.ImageField(upload_to='project_images/')),
            ],
        ),
    ]
